### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by koluacik** [koluacik/matrixlib#2]
- [ ] Complete this list
- [ ] Remove external variables
- [ ] Rational numbers
- - [ ] Rational numbers struct
- - [ ] Arithmetic operations functions
- - [ ] Comparison functions
- - [ ] Convert existing functions
- [ ] Check existing functions
